[build.system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pyjam10"
dynamic = ["version"]
dependencies = ["arcade", "pyinstaller"]

[project.scripts]
pyjam10 = "pyjam10.cli:run"

[tool.setuptools.dynamic]
version = { attr = "pyjam10.__version__" }
