[project]
name = "pyjam7"
dynamic = ["version"]

[tool.setuptools.dynamic]
version = { attr = "pyjam7.__version__" }

[tool.setuptools.packages.find]
where = ["src"]

[build.system]
requires = ["setuptools>=65.5"]
build-backend = "setuptools.build_meta"
